language: php

# the current Travis VMs are based on Ubuntu Trusty. Alas, those do not have php 5.3 available. So we keep using Precise...
dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  # This is mandatory or the 'apt-get install' calls following will fail
  - sudo apt-get update -qq || echo 'apt problems...'
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo apt-get install -y privoxy

install:
  # NB: the lib does not declare dependencies for now...
  - composer install

before_script:
  # Disable xdebug
  - phpenv config-rm xdebug.ini

  # Set up Apache and Privoxy instances inside the Travis VM and use them for testing against
  - ./test/ci/travis/setup_php_fpm.sh;
  - ./test/ci/travis/setup_apache.sh
  - ./test/ci/travis/setup_privoxy.sh

script:
  # Travis currently compiles PHP with an oldish cURL/GnuTLS combination;
  # to make the tests pass when Apache has a bogus SSL cert whe need the full set of options below
  php -d "include_path=.:./lib:./test" test/testsuite.php LOCALSERVER=localhost URI=/demo/server/server.php HTTPSSERVER=localhost HTTPSURI=/demo/server/server.php PROXY=localhost:8080 HTTPSVERIFYHOST=0 HTTPSIGNOREPEER=1 SSLVERSION=3

after_failure:
  # Save as much info as we can to help developers
  - cat apache_error.log
  - cat apache_access.log
  - php -i

# reduce depth (history) of git checkout
git:
    depth: 5
