language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_install:
  # This is mandatory or the 'apt-get install' calls following will fail
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi
  - sudo apt-get install -y privoxy

install:
  # NB: the lib does not declare dependencies for now...
  - composer self-update && composer install

before_script:
  # Disable xdebug. NB: this should NOT be done for hhvm...
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ]; then phpenv config-rm xdebug.ini; fi


  # Set up Apache and Privoxy instances inside the Travis VM and use them for testing against
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./test/ci/travis/setup_php_fpm.sh; ./test/ci/travis/setup_apache.sh; fi
  - if [ "$TRAVIS_PHP_VERSION" = "hhvm" ]; then ./test/ci/travis/setup_hhvm.sh; ./test/ci/travis/setup_apache_hhvm.sh; fi
  - ./tests/ci/travis/setup_privoxy.sh

script:
  php -d "include_path=.:./lib:./test" test/testsuite.php LOCALSERVER=localhost URI=/demo/server/server.php HTTPSSERVER=localhost HTTPSURI=/demo/server/server.php HTTPSVERIFYHOST=0 HTTPSIGNOREPEER=1 NOPROXY=1
